# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUIInfinityaScrollSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftUIInfinityScroll', :git => 'https://github.com/kazuooooo/SwiftUIInfinityScroll'

  # Pods for SwiftUIInfinityaScrollSample

end
